create table feature_snapshots (
    id bigint generated by default as identity primary key,

    snapshot_time timestamptz not null,
    window_hours integer not null,
    record_count integer not null,

    dht11_temperature_average double precision,
    dht11_temperature_median double precision,
    dht11_temperature_min double precision,
    dht11_temperature_max double precision,

    dht11_humidity_average double precision,
    dht11_humidity_median double precision,
    dht11_humidity_min double precision,
    dht11_humidity_max double precision,

    dht20_temperature_average double precision,
    dht20_temperature_median double precision,
    dht20_temperature_min double precision,
    dht20_temperature_max double precision,

    dht20_humidity_average double precision,
    dht20_humidity_median double precision,
    dht20_humidity_min double precision,
    dht20_humidity_max double precision,

    gas_raw_average double precision,
    gas_raw_median double precision,
    gas_raw_min double precision,
    gas_raw_max double precision,

    light_average double precision,
    light_median double precision,
    light_min double precision,
    light_max double precision,

    dht20_temperature_range double precision,
    dht20_humidity_range double precision,
    temperature_sensor_difference double precision,
    gas_range double precision,
    light_range double precision
);