name: Cron Test

on:
  schedule:
    - cron: "*/8 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Scheduled execution test
        run: |
          echo "================================"
          echo "CRON WORKFLOW EXECUTED"
          echo "UTC:"
          date -u
          echo "================================"
